server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    static_configs:
      - targets: [localhost]
        labels:
          job: docker-logs
          app: loki                     # label fixa para o dashboard da comunidade
          __path__: /var/lib/docker/containers/*/*-json.log

    pipeline_stages:
      - docker: {}                     # converte logs do formato Docker JSON
      - logfmt: {}                      # interpreta logs no formato key=value
      - labels:
          level: ""                     # transforma 'level' em label do Loki
